### PR TITLE
Add support for typed properties

### PR DESCRIPTION
**Pull request by tamatias**
Tiled version 0.16 introduced support for properties with types, these additions to the library add a way to access this type information.

In addition, `PropertySet` now uses an `unordered_map` instead of a `map` to store its properties (for faster access by key in large property sets.)

### CODE REVIEW

**Comment by sainteos** [comment]
Hey @andrewrk  can we get this and #44 merged?  I'm currently in need of the new style properties.  Thx :)

**Comment by andrewrk** [comment]
@sainteos want to become maintainer of the project?

**Comment by andrewrk** [comment]
I'm focused on other stuff right now and I would love to hand this off to someone who could keep it maintained better than I can.

**Comment by sainteos** [comment]
@andrewrk Yes, I would totally be down for that!

**Comment by andrewrk** [comment]
:zap: godspeed. :zap:

**Comment by sainteos** [comment]
Thank you :)

**Comment by sainteos** [comment]
+1. Was working on getting this merged (had to do it locally), though trying to figure out why github doesn't see it as merged.

**Pull request merged**
